version: 2
workflows:
  version: 2
  build:
    jobs:
      - build-latest
      - build-1.12
  scheduled:
    triggers:
      - schedule:
          cron: "1 2 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-latest
      - build-1.12

jobs:
  build-latest: &build-template
    docker:
      - image: circleci/golang:latest

    working_directory: /go/src/github.com/x-way/ctrmd
    steps:
      - checkout
      - run: go version
      - run: go get golang.org/x/lint/golint
      - run: go get -v -t -d ./...
      - run: go vet ./...
      - run: golint -set_exit_status ./...
      - run: go test -v ./...
      - run:
          name: codecov
          command: |
                    PATH=/tmp/sbin:$PATH go test -race -coverprofile=coverage.txt -covermode=atomic
                    bash <(curl -s https://codecov.io/bash)

  build-1.12:
    <<: *build-template
    docker:
      - image: circleci/golang:1.12
